### ISSUE TITLE
Get fbbt annotations from CATMAID

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/VFB_reporting#12]
Add fbbt annotations to neuron mapping tables where these are already present in CATMAID.

@mmc46 - what is the best way to pull fbbt annotations out of CATMAID for FAFB neurons?

**Comment by mmc46** [comment]
You can do it through R, python, via the API or CATMAID. Depends what tools you’re used to.

They all have functions to get the annotations from one or more skids. 

https://natverse.github.io/rcatmaid/reference/#section-names-and-annotations <https://natverse.github.io/rcatmaid/reference/#section-names-and-annotations>

https://pymaid.readthedocs.io/en/latest/source/example_gallery.html <https://pymaid.readthedocs.io/en/latest/source/example_gallery.html>

In CATMAID: use the Neuron Search widget, and 

‘annotated:/^FBbt’

Click ‘show annotation’, ’Submit’. Select every neuron using the tick mark and ‘Export CSV’.
