### ISSUE TITLE
Extend CATMAID VFB comparison table to count all neurons directly annotated *only* with 'neuron'

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_reporting#17]
We need a way to quickly see the extend of annotation in this reporting table:

https://github.com/VirtualFlyBrain/VFB_reporting_results/blob/master/L1EM_comparison.tsv

Add a column that counts how many individuals are *only* directly typed as neuron. Sketch:

```cql
MATCH (s:Site)<-[]-(i:Individual)-[:INSTANCEOF]->(c:Class { label: neuron})  
WHERE site.label = ??? return i.short_form, i.label, c.label
```

Set site to one of two CATMAIDs.  Use code to check whether only one classification for i.

**Comment by dosumis** [comment]
Hi Clare - can  you commit to this for this next sprint?

**Comment by Clare72** [comment]
Ok, will have a go. I see it is already in sprint_backlog

**Comment by dosumis** [comment]
Would be good to generate mapping tables for neurons with only general classification too - one per dataset + a set of cards on the data_staging board to track them.   May be easiest if you write code for generating mapping tables at same time.  Presumaby you could re-use code you wrote for generating list of new skids to map?
