### ISSUE TITLE
CATMAID new neuron mapping table

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/VFB_reporting#2]
Need an output table with the following for SKIDs found in CATMAID, but not VFB:

SKID (from CATMAID) | name (from CATMAID) | [optional - Paper | Paper FBrf |] FBbt (to be filled out) 

May need other columns to use in add_anatomy_image_set function in KB_tools.py

**Comment by dosumis** [comment]
This is basically what we discussed on VFB ont call.   Moving to in progress
