### ISSUE TITLE
FAFB reports don't find Individuals only classified as neuron

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_reporting#24]
253 FAFB skids: (https://github.com/VirtualFlyBrain/VFB_reporting_results/blob/master/EM_CATMAID_FAFB_skids.tsv) . 

Only 139 are mapped to an FBbt term in FAFB CATMAID https://github.com/VirtualFlyBrain/VFB_reporting_results/blob/master/FAFB_CAT_cellType_skids.tsv

But almost all are in  VFB KB:

```cql
MATCH (s:Site { short_form: 'VFBsite_catmaid_fafb'})
<-[:hasDbXref]-(i:Individual) return count (distinct i)
```
=> 252 neurons

112 are curated to neuron (Note this does not test 'neuron only - but the numbers almost match.)

```cql
MATCH (s:Site { short_form: 'VFBsite_catmaid_fafb'})
<-[:hasDbXref]-(i:Individual)-[:INSTANCEOF]->(c:Class)
 RETURN DISTINCT c.label, count (DISTINCT i)
```

c.label | count (distinct i)
-- | --
"adult antennal lobe projection neuron VM7v adPN" | 1
"adult antennal lobe projection neuron DL2v adPN" | 3
"adult antennal lobe projection neuron VA1d adPN" | 2
"neuron" | 112
"adult antennal lobe projection neuron DL1 adPN" | 1
"adult antennal lobe projection neuron VA6 adPN" | 1
...

But https://github.com/VirtualFlyBrain/VFB_reporting_results/blob/master/FAFB_comparison.tsv &  https://github.com/VirtualFlyBrain/VFB_reporting_results/blob/master/FAFB_neuron_only_skids.tsv  don't find any terms classified as only neurons

**Comment by dosumis** [comment]
This is likely just a symptom of code not finding matching VFB individuals for FAFB - see  https://github.com/VirtualFlyBrain/VFB_reporting_results/blob/master/FAFB_comparison.tsv.

I suspect this is down to where SKIDS are being looked up in KB - on the IRW edge.  Standard loading code makes these dbxrefs -> site.  Location in IRW edge for L1 EM is due to Robbie's (not defunct?) loading code.  Should be easy to switch.

**Comment by dosumis** [comment]
Code also uses CATMAID paper ids, stored in `ds.catmaid_annotation_id`  Not present for FAFB.

**Comment by dosumis** [comment]
### Schema proposal (generic solution to recording IDs & other details needed for API calls)

1. We should make API nodes (distinct from Site nodes) for CATMAID APIs, FlyCircuit API etc.  Wit this in place, we can reserve xrefs to Site nodes for Link-outs from the VFB website.
2. We should record keys and values for API calls as xrefs from the relevant nodes in VFB KB to these API nodes.

e.g. 
```cql
(ds:DataSet)-[:hasDbXref { acc: 13040382,  property: 'annotated_with:paper_id'} ]
->(:API { label: 'FAFB CATMAID API', iri: 'https://fafb.catmaid.virtualflybrain.org'})
```

This might not be fully sufficient to roll API calls, but we could add free text comments on the API nodes to document recipes.

Question: Do the IDs we need to link to in CATMAID in this case refer to papers or DataSets.  From their names and usage (paper_id, published) , they appear to refer to papers. If so, the subject of the relationship above could (should) be the relevant pub rather than to DataSet.  Practical consideration:  Do we get new IDs in CATMAID when a preprint becomes a full pub?

Please review @mmc46, @Robbie1977, @Clare72

**Comment by dosumis** [comment]
@mmc46 - any strong opinions on whether we  should attach CATMAID FAFB.paper_id to paper or dataset in VFB?

**Comment by mmc46** [comment]
I think CATMAID FAFB.paper_id should be attached to paper. 
A neuron might be included in more than one paper.

> Practical consideration: Do we get new IDs in CATMAID when a preprint becomes a full pub?
Not sure what type of IDs you're referring to. Skeleton ids will remain the same. If a neuron is part of a preprint that is released, and later of a publication, it will have an annotation for each (each annotation has its own annotation ID).

**Comment by dosumis** [comment]
Hi Marta,

I think we have crossed wires here.  We currently have nodes for datasets and paper and sites:  

```cql
(neuron)-[:has_souce]->(dataset)-[:reference]->(pub)
(neuron)-[:hasDBXref {accession : <some SKID> ]->(s:Site { name: 'FAFB CATMAID'})
```

Neurons can belong to multiple datasets.  A single dataset could potentially be linked to multiple pubs (althouth we have no examples of this right now).  I guess the confusion comes from that CATMAID has not concept of datasets - just publications.

> > Practical consideration: Do we get new IDs in CATMAID when a preprint becomes a full pub?

> Not sure what type of IDs you're referring to

Here I'm refering to the paper_id.  Would there be a new paper_id when the preprint becomes a full pub?

**Comment by mmc46** [comment]
>I guess the confusion comes from that CATMAID has not concept of datasets - just publications.
CATMAID has no concept of publications either. We use regular annotations (each annotation has an ID) to group neurons - for this purpose, using an annotation string that identifies the publication (last author, year). 
We could to the same for datasets if you wanted, though as data is being released per publication, it would be redundant and I don't think it is helpful in this case.

Can you give me an example of a paper_id?

**Comment by dosumis** [comment]
FAFB query is for `annotated_with`:`Published`
(see https://github.com/VirtualFlyBrain/VFB_reporting/blob/23c784b2c2d5bd750f5e0a7a03cbb4d1583ba5b9/src/get_catmaid_papers.py#L26
+
https://github.com/VirtualFlyBrain/VFB_reporting/blob/master/src/comparison.py#L15)

resulting accessions in paper_id column here: https://github.com/VirtualFlyBrain/VFB_reporting_results/blob/master/FAFB_comparison.tsv

**Comment by mmc46** [comment]
So as I thought paper_id is the annotation ID. We have, so far, only been releasing data for full publications, not including preprints. As the papers so far have either been directly published or preprint and then published.

But if we wanted to do a release for both the preprint and publication they would have different IDs (because they would have different annotations).

**Comment by dosumis** [comment]
Steps needed to fix:

1. Decide on schema
2. Add missing CATMAID content to correct loc in KB:  
   1. Move skids (if needed)
   2. One off script with CATMAID API access to add whatever we are calling the annotation id that sort of refers to publications. 
3. Update reporting scripts.
3. Longer term - we need to write pipeline scripts that wrap KB pattern loader methods.  This could be via generation of curation TSVs for review & loading - or could be direct.  Might be best to use direct method for FAFB given that we can load with Classification.

**Comment by dosumis** [comment]
KB Fixes:

1. added API nodes:
```cql
CREATE (:API { label: 'L1EM CATMAID API', short_form: 'l1em_catmaid_api', iri: 'http://virtualflybrain.org/apis/l1em_catmaid_api', homepage: 'https://l1em.catmaid.virtualflybrain.org/apis/'})
CREATE (:API { label: 'FAFB CATMAID API', short_form: 'fafb_catmaid_api', iri: 'http://virtualflybrain.org/apis/fafb_catmaid_api', homepage: 'https://fafb.catmaid.virtualflybrain.org/apis/'})
```
2. Adding links directly from DataSets (Maybe review this in future - but direct is easier for querying)

```cql
MATCH (ds:DataSet)<-[:has_source]-(i:Individual)-[:hasDbXref]->(s:Site) 
WHERE exists(ds.catmaid_annotation_id) AND s.short_form = 'catmaid_l1em' 
WITH distinct ds, ds.catmaid_annotation_id AS paper_id 
MATCH (api:API { short_form: 'l1em_catmaid_api'}) 
MERGE (ds)-[r:hasDbXref]->(api) 
SET r.accession = paper_id SET r.property = 'annotated_with:papers'

MATCH (ds:DataSet)<-[:has_source]-(i:Individual)-[:hasDbXref]->(s:Site) 
WHERE exists(ds.catmaid_annotation_id) AND s.short_form = 'catmaid_fafb' 
WITH distinct ds, ds.catmaid_annotation_id AS paper_id 
MATCH (api:API { short_form: 'fafb_catmaid_api'}) 
MERGE (ds)-[r:hasDbXref]->(api) 
SET r.accession = paper_id SET r.property = 'annotated_with:Published'
```
