### ISSUE TITLE
Script automated generation of linkout tables  & posting to GitHub.

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_reporting#26]
These should  follow FlyBase linkout table structure.

We may be able to re-use reporting infrastructure to do this.

Sketch of queries:

1. Find  all  site nodes:
2. Iterate over site nodes, pulling any dbxref link with an acc -> table for each site
3. For links  to individuals, generate thumbnail image link.

Images from classes are more of a challenge.  May need to be custom script, as needed - or perhaps just configurable per Site.

**Comment by dosumis** [comment]
Linkout examples (current)

VFB_linkout.tsxt
|#FlyBase ID	| DBNAME | DBID |	DBURL
--- | --- | ---| ---
FBtp0059415	| VFB  |	VFB_00021850	| VFB_00021850

```tsv
DBNAME	VFB
BASEURL	http://virtualflybrain.org/reports/
HOMEURL	http://www.virtualflybrain.org/
DESC	A database to explore neuroanatomy, connectivity and gene expression
EMAIL	mmc46@cam.ac.uk
```


VFB_dbinfo.txt


ftp://ftp.flybase.org/flybase/linkout_providers/vfb/

The files in the location above look like the standard linkout format for linkouts and are FBtp to VFB links, so I think that it'll probably be standard linkout format that is needed. I don't know how VFB has provided thumbnails in the past, so that may be an additional requirement in addition to the linkout files.

**Comment by dosumis** [comment]
(See https://github.com/VirtualFlyBrain/Management/issues/220)

**Comment by admclachlan** [comment]
closing, new FB > VFB linkouts enhancement issue https://github.com/VirtualFlyBrain/Management/issues/342
