### ISSUE TITLE
Add reports of number of expression annotations to summary reports

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_reporting#39]
Queries: 

```cql
MATCH p=(split:Class:Split)<-[r:part_of]-(j:Individual)-[:INSTANCEOF]->(n:Neuron:Class) 
WHERE exists(r.pub) 
RETURN count(distinct split) AS Splits, count(r) AS annotations, count(distinct n) as neurons
```

```cql
MATCH p=(ep:Class:Expression_pattern)<-[r:part_of|overlaps]-(j:Individual)-[:INSTANCEOF]->(n:Class) 
WHERE exists(r.pub) 
RETURN count(distinct ep) AS EPs, count(r) AS annotations, count(distinct n) as anatomy
```

```cql
MATCH p=(ep:Class:Expression_pattern)<-[r:part_of]-(j:Individual)-[:INSTANCEOF]->(n:Neuron:Class) 
WHERE exists(r.pub) 
RETURN count(distinct ep) AS EPs, count(r) AS annotations, count(distinct n) as neurons
```

**Comment by Clare72** [comment]
Maybe I should say 'annotations' instead of 'images', but does (j:Individual)-[:INSTANCEOF]->(n:Neuron:Class)  restrict to where there is an image showing a single type?

**Comment by dosumis** [comment]
These are annotations about expression coming from FlyBase, not images.

**Comment by dosumis** [comment]
Maybe phrase as:

"Annotations recording the types of neurons specific split combinations are expressed in. "
"Annotations recording the types of anatomical structures or cell types specific driver lines are expressed in"
"Annotations recording the types of neurons specific driver lines are expressed in"
