### ISSUE TITLE
VFB ontology content reporting

### ISSUE THREAD

**Issue by Clare72** [VirtualFlyBrain/VFB_reporting#4]
We need generic report generation scripts for this. These can run off pdb with a very simple wrapper

e.g. 

```cql
MATCH (n:Neuron:Class)
WITH n OPTIONAL MATCH (n)-[r:has_reference]-(p:pub) 
RETURN count(distinct n), count(distinct p)
```
=> counts of neurons and pubs curated for them.

**Comment by dosumis** [comment]
@dosumis to make subtickets. 

number of neurons & number of pubs 
total number terms & number pubs
number of  nervous system parts 
number of sense organs

Use neo4J labels where possible, e.g. :Neuron. Where these don't exist use Cypher queries or OWLery queries. 

e.g. 
owlery query for subclasses of "'overlaps' some 'nervous system'" -> 
MATCH (n:Class) WHERE n.iri in [...] WITH n OPTIONAL MATCH (n)-[r:has_reference]-(p:pub) return count(distinct n), count(distinct p)

**Comment by dosumis** [comment]
@Clare72  - Have assigned to you as should be  straightforward given info on this ticket. Let  me know if you  need help.
