### ISSUE TITLE
Make VFB server diff reports easier to understand

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_reporting#47]
Use case:  As a VFB curator/Dev I want to know what publicly released data has _failed_ to make it through the pipeline from KBW to dev, staging, prod.

We currently have diff tables generated by 

https://github.com/VirtualFlyBrain/VFB_reporting/blob/master/src/reporting_tools.py#L86

but these are not so easy to understand.   

AIM: work out how to make these reports clearer.  Right now they just list all the contents of datasets in the production/dev/staging neo where those contents differ in any way from contents on KB.  It would be better if we explicitly displayed these differences in each case (contents on KB vs contents on prod/staging/dev).

Also check they run automatically/regularly (@Robbie1977  - isn't there a cron job or equivalent for these? - triggered by https://github.com/VirtualFlyBrain/VFB_reporting/blob/master/src/report_runner.py)

**Comment by dosumis** [comment]
Side issue - this should be `overlaps|part_of` for expression patterns.

https://github.com/VirtualFlyBrain/VFB_reporting/blob/master/src/reporting_tools.py#L68

**Comment by Robbie1977** [comment]
The reports all appear to be working and are quite useful.

**Comment by Robbie1977** [comment]
Probably worth sorting by state (production null at top etc)

**Comment by Clare72** [comment]
So @dosumis - do I understand correctly that instead of having the absolute number of items in the diff reports, you want to actually do the subtraction and show the difference in number of items?

**Comment by dosumis** [comment]
That might be tricky.  We could instead show 2 lines - one for KB and one for the prod instance - side by side so that we can view the difference.

**Comment by Clare72** [comment]
I think it should be possible with [pandas subtract](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.subtract.html)
But if you prefer side by side, that should be possible too
