### ISSUE TITLE
Make Jenkins job to generate reports and commit them to GitHub

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_reporting#5]
The Travis job on vfb_reporting runs test builds of various TSV reports about the state of data in the kb, and various pdb instances + diffs highlighting differences in content.  We are working on adding similar reports for CATMAID - comparing content to KB.  All of these reports should also be generated by a Jenkins job and committed back to this repo in a reports/ folder.

**Comment by Robbie1977** [comment]
Results appear in https://github.com/VirtualFlyBrain/VFB_reporting_results

**Comment by dosumis** [comment]
Cool!  Thanks for doing this so quickly.  Can you Slack me a link to the Jenkins job (or to whatever is running this if not Jenkins.)?

**Comment by Robbie1977** [comment]
Done by travis https://github.com/VirtualFlyBrain/VFB_reporting/blob/master/.travis.yml#L26

I've also set up a cron job to run every day on travis from now on.
